/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.finPessoal.fonte;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadContaFinanceira extends javax.swing.JDialog {

    private String id, metodo;
    private ConBanco cb = new ConBanco();
    private ConexaoClass cc = cb.IniciarBd();
    
    /**
     * Creates new form CadContaFinanceira
     */
    public CadContaFinanceira(java.awt.Frame parent, boolean modal, String id, String metodo) {
        super(parent, modal);
        initComponents();
        
        setMetodo(metodo);
        setId(id);
        
        if(metodo.equals("U") || metodo.equals("D")){
            CarregaDados();
        }else if(metodo.equals("C")){
            GerarId gi = new GerarId("receitadespesa");
            lbID.setText(gi.getProximoId());
        }
        
        //colocar a janela no meio da tela
        this.setLocationRelativeTo(null);
        
        GetConfig gc = new GetConfig();
        this.setIconImage(gc.getIco());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbReceitaDespesa = new javax.swing.JComboBox();
        chGrupo = new javax.swing.JCheckBox();
        chFixa = new javax.swing.JCheckBox();
        chAtivo = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        tfCodPai = new javax.swing.JTextField();
        lbNomePai = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfCodigo = new javax.swing.JTextField();
        btBuscarInfoPai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Conta Financeira");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(480, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbID.setText("lbID");
        getContentPane().add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, -1));

        jLabel4.setText("Receita/Despesa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbReceitaDespesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receita", "Despesa" }));
        getContentPane().add(cbReceitaDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        chGrupo.setText("Grupo");
        getContentPane().add(chGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        chFixa.setText("Fixa");
        getContentPane().add(chFixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        chAtivo.setText("Ativo");
        getContentPane().add(chAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel5.setText("Conta Pai:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        tfCodPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodPaiActionPerformed(evt);
            }
        });
        getContentPane().add(tfCodPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, -1));

        lbNomePai.setText("lbNomePai");
        getContentPane().add(lbNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 290, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/save.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        btBuscarInfoPai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/find.png"))); // NOI18N
        btBuscarInfoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarInfoPaiActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarInfoPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodPaiActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btBuscarInfoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarInfoPaiActionPerformed
        
        lbNomePai.setText(getPaiNome(tfCodPai.getText()));
        
    }//GEN-LAST:event_btBuscarInfoPaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //captura os valores para montar o comando
        String sql, rd_id, rd_codigo, rd_nome, rd_receita_despesa, rd_pai, usuario_id, rd_grupo, rd_ativo, rd_fixa;
        rd_id = lbID.getText();
        rd_codigo = tfCodigo.getText();
        rd_nome = tfNome.getText();
        rd_receita_despesa = getReceitaDespesaChar(cbReceitaDespesa.getSelectedItem().toString());
        rd_pai = (tfCodPai.getText().equals("") ? null : tfCodPai.getText());
        usuario_id = "1";
        rd_grupo = getCheckBoxValor(chGrupo);
        rd_ativo = getCheckBoxValor(chAtivo);
        rd_fixa = getCheckBoxValor(chFixa);
        
        if(getMetodo().equals("C") || getMetodo().equals("U")){//criar e alterar
            
            if(getMetodo().equals("C")){
                sql = "INSERT INTO receitadespesa VALUES("+rd_id+",";
                sql += "'"+rd_codigo+"',"+usuario_id+", '"+rd_nome+"',";
                sql += "'"+rd_receita_despesa+"',"+rd_pai+",";
                sql += "'"+rd_grupo+"','"+rd_fixa+"','"+rd_ativo+"')";
                
                
                
                
            }else{
                sql = "UPDATE receitadespesa SET CODIGO = '"+rd_codigo+"',";
                sql += "nome = '"+rd_nome+"', receita_despesa = '"+rd_receita_despesa+"',";
                sql += "rd_pai = "+rd_pai+", grupo = '"+rd_grupo+"',";
                sql += "fixa = '"+rd_fixa+"', ativo = '"+rd_ativo+"' ";
                sql += " where id = "+rd_id;
                 
            }
            
            try{
                cc.stm.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Dados gravados com sucesso!");
                    
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Erro ao gravar dados!\n"+e.getMessage());
            }
            
        }else{//deletar
            try{
                
                int jp = JOptionPane.showConfirmDialog(this, "Desejas realmente excluir esse registro?");
                
                if(jp == 0){
                    cc.stm.executeUpdate("DELETE FROM receitadespesa WHERE ID = "+rd_id);

                    JOptionPane.showMessageDialog(this, "Dados excluidos com sucesso!");
                }
                    
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Erro ao excluir dados!\n"+e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadContaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadContaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadContaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadContaFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadContaFinanceira dialog = new CadContaFinanceira(new javax.swing.JFrame(), true,"","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarInfoPai;
    private javax.swing.JComboBox cbReceitaDespesa;
    private javax.swing.JCheckBox chAtivo;
    private javax.swing.JCheckBox chFixa;
    private javax.swing.JCheckBox chGrupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNomePai;
    private javax.swing.JTextField tfCodPai;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    //get e set
    public void setId(String id){
        this.id = id;
    }
    
    public void setMetodo(String metodo){
        this.metodo = metodo;
    }
    
    public String getId(){
        return this.id;
    }
    
    public String getMetodo(){
        return this.metodo;
    }

    private void CarregaDados() {
        
        String receitaDespesa,idPai = "0";
        
        try{
            ResultSet rsContaFin = cc.stm.executeQuery("SELECT * FROM receitadespesa where id = '"+getId()+"'");
            
            if(rsContaFin.next()){
                
                lbID.setText(rsContaFin.getString("ID"));
                tfCodigo.setText(rsContaFin.getString("CODIGO"));
                tfNome.setText(rsContaFin.getString("NOME"));
                tfCodPai.setText(rsContaFin.getString("RD_PAI"));
                
                cbReceitaDespesa.setSelectedItem(getReceitaDespesa(rsContaFin.getString("RECEITA_DESPESA")));
                
                idPai = rsContaFin.getString("RD_PAI");
                
                setCheckBox(rsContaFin.getString("GRUPO"), chGrupo);
                setCheckBox(rsContaFin.getString("FIXA"), chFixa);
                setCheckBox(rsContaFin.getString("ATIVO"), chAtivo);
                
                
            }else{
                JOptionPane.showMessageDialog(this, "Não foi possivel encontrar os dados!");
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados!\n"+e.getMessage());
        }
        
        lbNomePai.setText(getPaiNome(idPai));
                
                
        
        //codigo receita_despesa
        
    }

    private void setCheckBox(String string, JCheckBox chbVal) {
        if(string.equals("S")){
            chbVal.setSelected(true);
        }else{
            chbVal.setSelected(false);
        }
    }
    
    private String getCheckBoxValor(JCheckBox chbVal){
        if(chbVal.isSelected()){
            return "S";
        }else{
            return "N";
        }
    }
    
    //captura o nome do pai
    
    public String getPaiNome(String idStr){
        
        try{
            ResultSet rsContaFin = cc.stm.executeQuery("SELECT * FROM receitadespesa where grupo = 'S' and id = '"+idStr+"'");
            
            if(rsContaFin.next()){
                
                return rsContaFin.getString("NOME");
                
             }else{
                return "";
            }
            
        }catch(SQLException e){
            return "";
        }
        
    }
    
    private String getReceitaDespesa(String string) {
        
        if(string.equals("R")){
            return "Receita";
        }else{
            return "Despesa";
        }
    }
    
    private String getReceitaDespesaChar(String string) {
        
        if(string.equals("Receita")){
            return "R";
        }else{
            return "D";
        }
    }

}
