/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.finPessoal.fonte;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormLancamentoFinanceiro extends javax.swing.JFrame {

    private String WhereStr;
    public ConBanco cb = new ConBanco();
    public ConexaoClass cc = cb.IniciarBd();
    private String Mensagem;
    
    /**
     * Creates new form FormContasFinanceiras
     */
    public FormLancamentoFinanceiro(String idUsuario, String tipoLancamento) {
        
        /*tipoLancamento
        terá 4 valores válidos
        RF = Receita Fixa
        RV = Receita Variada
        DF = Despesa Fixa
        DV = Despesa Variada
        
        */
        
        
        initComponents();
        
        GeralClass geralClass = new GeralClass();
        geralClass.setCarregaComboMes(cbMes);
        tfAno.setText(geralClass.getAnoAtual());
        cbMes.setSelectedItem(geralClass.getMesAtualExt());
        
        System.out.println(geralClass.getMesAtual());
        
        setWhere(geralClass.getMesAtual(), geralClass.getAnoAtual(), "");
        
        MontarTabela("");
        
        //colocar a janela no meio da tela
        this.setLocationRelativeTo(null);
        
        lbUsuarioNome.setText(cb.getUsuarioNome(idUsuario));
        
        GetConfig gc = new GetConfig();
        this.setIconImage(gc.getIco());
        
        lbMsg.setText(getMensagem());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        tfBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbUsuarioNome = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox();
        tfAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConFin = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btPrimeiro = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setTitle("Contas Financeiras");

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/create.png"))); // NOI18N
        btIncluir.setText("Novo");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/alter.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/find.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Contas Financeiras");

        lbUsuarioNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbUsuarioNome.setText("Nome do Úsuario");

        lbMsg.setForeground(new java.awt.Color(51, 102, 255));
        lbMsg.setText("Mensagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbUsuarioNome)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbUsuarioNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(btAtualizar)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMsg)
                .addContainerGap())
        );

        tbConFin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Conta Financeira", "Nome", "Data Base", "Quitado", "L/M/C", "Documento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConFin);

        btPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/tostart.png"))); // NOI18N
        btPrimeiro.setToolTipText("Primeiro Registros");

        btAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/backward.png"))); // NOI18N
        btAnterior.setToolTipText("Registros Anteriores");

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/foward.png"))); // NOI18N
        btProximo.setToolTipText("Próximos registros");

        btUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/toend.png"))); // NOI18N
        btUltimo.setToolTipText("Final da Lista");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUltimo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrimeiro)
                    .addComponent(btAnterior)
                    .addComponent(btProximo)
                    .addComponent(btUltimo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        String where = "";
        where = tfBuscar.getText();
        GeralClass geralClass = new GeralClass();
            
        if(!where.equals("")){
            
            setWhere(geralClass.getMesNumerico(cbMes.getSelectedItem().toString()), tfAno.getText(), where);
            MontarTabela(getWhere());
        
        }else{
        
            setWhere(geralClass.getMesNumerico(cbMes.getSelectedItem().toString()), tfAno.getText(), "");
            MontarTabela(getWhere());
        
        }

    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed

        String where = "";
        where = tfBuscar.getText();
        GeralClass geralClass = new GeralClass();
            
        if(!where.equals("")){
            
            setWhere(geralClass.getMesNumerico(cbMes.getSelectedItem().toString()), tfAno.getText(), where);
            MontarTabela(getWhere());
        
        }else{
        
            setWhere(geralClass.getMesNumerico(cbMes.getSelectedItem().toString()), tfAno.getText(), "");
            MontarTabela(getWhere());
        
        }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linha = -1;
        if(tbConFin.getSelectedRow() >= 0){
            linha = tbConFin.getSelectedRow();
        }
        String valor = "";
        if(tbConFin.getValueAt(linha, 0).toString() != null){
            valor = (tbConFin.getValueAt(linha, 0)).toString();
        }

        if(valor.isEmpty() || valor.equals("") || valor == null){
            JOptionPane.showMessageDialog(this, "Por favor! Selecione um registro!");
        }else{
            new CadContaFinanceira(this, true,valor,"D").setVisible(true);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        int linha = -1;
        if(tbConFin.getSelectedRow() >= 0){
            linha = tbConFin.getSelectedRow();
        }
        String valor = "";
        if(tbConFin.getValueAt(linha, 0).toString() != null){
            valor = (tbConFin.getValueAt(linha, 0)).toString();
        }

        if(valor.isEmpty() || valor.equals("") || valor == null){
            JOptionPane.showMessageDialog(this, "Por favor! Selecione um registro!");
        }else{
            new CadContaFinanceira(this, true,valor,"U").setVisible(true);
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        new CadContaFinanceira(this, true,"0","C").setVisible(true);

    }//GEN-LAST:event_btIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLancamentoFinanceiro("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbUsuarioNome;
    private javax.swing.JTable tbConFin;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables

    private void MontarTabela(String where) {
        
        int linha = 0;
        int coluna = 0;
        
        while(linha < 25){
            while(coluna < 7){
                tbConFin.getModel().setValueAt("", linha, coluna);
                coluna++;
            }
            linha++;
            coluna = 0;
        }
        
        linha = 0;
        
        String rd_id
                ,rd_codico
                ,rd_nome
                ,rd_receita_despesa
                ,rd_grupo
                ,rd_fixa
                ,rd_ativo;
        
        
        
        try{
            ResultSet rsConFin = cc.stm.executeQuery("select * from lancamento_financeiro "+where+" order by nome limit 25");
            
            while ( rsConFin.next() ) {
                rd_id       = rsConFin.getString("RD_ID");
                rd_codico   = rsConFin.getString("rd_codico");
                rd_nome     = rsConFin.getString("rd_nome");
                rd_receita_despesa = getRecDesp(rsConFin.getString("rd_receita_despesa"));
                rd_grupo    = getSimNao(rsConFin.getString("rd_grupo"));
                rd_fixa     = getSimNao(rsConFin.getString("rd_fixa"));
                rd_ativo    = getSimNao(rsConFin.getString("rd_ativo"));
                
                tbConFin.getModel().setValueAt(rd_id, linha, 0);
                tbConFin.getModel().setValueAt(rd_codico, linha, 1);
                tbConFin.getModel().setValueAt(rd_nome, linha, 2);
                tbConFin.getModel().setValueAt(rd_receita_despesa, linha, 3);
                tbConFin.getModel().setValueAt(rd_grupo, linha, 4);
                tbConFin.getModel().setValueAt(rd_fixa, linha, 5);
                tbConFin.getModel().setValueAt(rd_ativo, linha, 6);
                
                linha++;
            }
            
            
            if(linha <= 10){
                setMensagem("A Busca retornou "+linha+" registros!");
                
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Erro ao Carregar informações de contas financeiras!\n"+e.getMessage());
        }
        
    }
    
    //Campos
    private String getSimNao(String t){
        if(t.equals("S")){
            return "Sim";
        }else{
            return "Não";
        }
    }
    
    private String getRecDesp(String t){
        if(t.equals("R")){
            return "Receita";
        }else{
            return "Despesa";
        }
    }
    
    public void setWhere(String mes, String ano, String where){
        this.WhereStr = " WHERE MES_BASE = '"+mes+"' AND ANO_BASE = '"+ano+"'";
        if(!where.equals("")){
            this.WhereStr += "AND NOME LIKE '"+where+"'";
        }
        
    }
    
    public String getWhere(){
        return this.WhereStr;
    }
    
    /*
    public void setWhereNav(String Cod){
        this.WhereStr = " WHERE RD_CODIGO > '"+Cod+"' ";
    }
    */
    public void setMensagem(String Mensagem){
        this.Mensagem = Mensagem;
    }

    public String getMensagem(){
        return this.Mensagem;
    }
}
