/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.finPessoal.fonte;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class FormPrincipal extends javax.swing.JFrame {

    private String idUsuario;
    public ConBanco cb = new ConBanco();
    public ConexaoClass cc = cb.IniciarBd();
    
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal(String idUsuario) {
        initComponents();
        
        //colocar a janela no meio da tela
        //this.setLocationRelativeTo(null);
        
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();  
        setSize(tela.width, tela.height);
        
        lbUsuarioNome.setText(cb.getUsuarioNome(idUsuario));
        
        setIdUsuario(idUsuario);
        
        GetConfig gc = new GetConfig();
        this.setIconImage(gc.getIco());
        
        //visual Windows
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuarioNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DespesasVariadas = new javax.swing.JMenuItem();
        DespesasFixas = new javax.swing.JMenuItem();
        ReceitasFixas = new javax.swing.JMenuItem();
        ReceitasVariadas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrada do Sistema");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuarioNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUsuarioNome.setText("Nome do Usuário");
        getContentPane().add(lbUsuarioNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        jMenu1.setText("Cadastros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/CadastroContasFinanceiras.png"))); // NOI18N
        jMenuItem1.setText("Contas Financeiras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lançamentos");

        DespesasVariadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Despesa.png"))); // NOI18N
        DespesasVariadas.setText("Despesas Variadas");
        jMenu2.add(DespesasVariadas);

        DespesasFixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Despesa.png"))); // NOI18N
        DespesasFixas.setText("Despesas Fixas");
        jMenu2.add(DespesasFixas);

        ReceitasFixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Receita.png"))); // NOI18N
        ReceitasFixas.setText("Receitas Fixas");
        jMenu2.add(ReceitasFixas);

        ReceitasVariadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Receita.png"))); // NOI18N
        ReceitasVariadas.setText("Receitas Variadas");
        jMenu2.add(ReceitasVariadas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configurações");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/finPessoal/fonte/img/Pessoas.png"))); // NOI18N
        jMenuItem4.setText("Usuários");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        System.out.println(getIdUsuario());
        
        new FormContasFinanceiras(getIdUsuario()).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPrincipal("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DespesasFixas;
    private javax.swing.JMenuItem DespesasVariadas;
    private javax.swing.JMenuItem ReceitasFixas;
    private javax.swing.JMenuItem ReceitasVariadas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbUsuarioNome;
    // End of variables declaration//GEN-END:variables


    public void setIdUsuario(String idUsuario){
        this.idUsuario = idUsuario;
    }
    
    public String getIdUsuario(){
        return this.idUsuario;
    }
    
}
